### ISSUE TITLE
Missing support for DD format

### ISSUE THREAD

**Issue by johnzanussi** [najlepsiwebdesigner/foundation-datepicker#108]
Older versions supported day of week label (Monday, Tuesday, Thursday, etc) format using 'DD'. Looking through the source code it does not appear that the `days` property of the `dates` object is referenced anywhere. Was this removed intentionally? 

https://github.com/najlepsiwebdesigner/foundation-datepicker/blob/master/js/foundation-datepicker.js#L1050

**Comment by najlepsiwebdesigner** [comment]
Hi!

This was surely not intentional, it was probably result of code merge with foundation-datetimepicker.
Currently, Im not able to fix this and I will no be able to do so in two weeks. If you can, you can do it and submit a pull request, if not, please install previous release.

Thank you

Odoslané z iPhonu

Dňa 29. 10. 2015, o 0:01, John Zanussi <notifications@github.com> napísal:
