### ISSUE TITLE
Increase Version Number

### ISSUE THREAD

**Issue by planetmalone** [najlepsiwebdesigner/foundation-datepicker#136]
Hello,

I'd like to get the latest version of the code that includes initialDate. Would you mind updating the version in package.json, so I don't have to target a specific commit?

Thanks!

**Comment by najlepsiwebdesigner** [comment]
Hi!

Im nit able to do that currently because Im in Vietnam without the pc right
now. Can you please do it and submit a pull request? I can then release new
version via web interface. Or you can wait until 23.3. when I return.
Thanks for understanding.

Dňa piatok, 11. marca 2016 Sean Malone <notifications@github.com>
napísal(a):

> Hello,
>
> I'd like to get the latest version of the code that includes initialDate.
> Would you mind updating the version in package.json, so I don't have to
> target a specific commit?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/najlepsiwebdesigner/foundation-datepicker/issues/136>.
>


-- 

Ing. Peter Beňo
--------------------------------
Web development & computer vision & robotics
http://peterbeno.com

**Comment by najlepsiwebdesigner** [comment]
new release added, 1.5.2
