### ISSUE TITLE
Uncaught TypeError: undefined is not a function 

### ISSUE THREAD

**Issue by hmihail** [najlepsiwebdesigner/foundation-datepicker#57]
I keep getting this error [ Uncaught TypeError: undefined is not a function ], and I am stuck with this for days now. Anyone have any idea?
Thanks!

**Comment by HermannHH** [comment]
Hi @vijayj ,

Were you ever able to implement a datepicker? I'm experiencing the same issue as you were and can confirm it is because of the reason listed above. The datetimepicker works flawlessly. I have tried to download the JS and CSS from the main project and pasting them into my app. It does allow for some functionality but does not function as smoothly as the datetimepicker. Also the CSS is a little bit messed up (Using Foundation 5)

**Comment by najlepsiwebdesigner** [comment]
Hi! 
Can you please describe what is the problem or provide us screenshot of bad CSS you mention? I can have a look. Basically, datepicker and datetimepicker are almost the same, so if datetimepicker works, datepicker should work also..

Thanks! 

Just to mention - problems in this thread were always in the end reported as solved. Usual problem is loading datepicker before jQuery.

**Comment by HermannHH** [comment]
![rsz_screenshot_from_2015-01-07_233657](https://cloud.githubusercontent.com/assets/5584878/5653852/92afe710-96c6-11e4-9767-b71097cbb814.png)

@najlepsiwebdesigner,

Thanks for the response. I have attached a screenshot of the issues. You'll be able to see the following 3 issues:
1)Dob input is no longer the right size (Should be the same width as the other inputs)
2) The Calendar is sometimes dislayed above the Input if there is not enough space for it below the Dob input
3) The spacing around the Dob form is no longer right. It now covers the Gender label.

I am sure this is some issue with Foundation 5. Thanks for the help!
